/* SPDX-License-Identifier: Bitstream-Vera */
/* SPDX-AI-Disclosure: ai-assisted */
/* SPDX-AI-Model: claude-opus-5-5 */
/* SPDX-AI-Provider: Anthropic */
/* SPDX-AI-Scope: glyph shapes from the DejaVu fonts (human-designed); converted to C by tools/ttf2qg.py, which is ai-generated */
/*******************************************************************************
 * Size: 16 px
 * Bpp: 1
 * Source: DejaVuSans.ttf
 * Generated by tools/ttf2qg.py (QG4P).
 * Layout: LVGL fmt_txt, uncompressed. The glyph shapes are covered
 * by the source font's licence.
 *******************************************************************************/

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

#ifndef QG_FONT_SANS_16
#define QG_FONT_SANS_16 1
#endif

#if QG_FONT_SANS_16

/*-----------------
 *    BITMAPS
 *----------------*/

/*Store the image of the glyphs*/
static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    /* U+0020 " " */

    /* U+0021 "!" */
    0xff, 0x30,

    /* U+0022 """ */
    0x99, 0x99,

    /* U+0023 "#" */
    0x0c, 0x81, 0x10, 0x26, 0x3f, 0xf1, 0x90, 0x22, 0x04, 0xc7, 0xfe, 0x32,
    0x04, 0x40, 0x98, 0x00,

    /* U+0024 "$" */
    0x10, 0x21, 0xf6, 0x99, 0x12, 0x1c, 0x0e, 0x12, 0x26, 0x5b, 0xe1, 0x02,
    0x00,

    /* U+0025 "%" */
    0x70, 0x44, 0x42, 0x22, 0x21, 0x13, 0x08, 0x90, 0x39, 0x00, 0x09, 0xc0,
    0x91, 0x0c, 0x88, 0x44, 0x44, 0x22, 0x20, 0xe0,

    /* U+0026 "&" */
    0x3c, 0x18, 0x84, 0x01, 0x00, 0x20, 0x14, 0x08, 0x86, 0x11, 0x82, 0x60,
    0x64, 0x18, 0xf9,

    /* U+0027 "'" */
    0xf0,

    /* U+0028 "(" */
    0x36, 0x44, 0x88, 0x88, 0x88, 0x44, 0x63,

    /* U+0029 ")" */
    0xc6, 0x22, 0x11, 0x11, 0x11, 0x22, 0x6c,

    /* U+002A */
    0x10, 0x22, 0x4b, 0xe3, 0x9a, 0xc4, 0x08,

    /* U+002B "+" */
    0x08, 0x04, 0x02, 0x01, 0x0f, 0xf8, 0x40, 0x20, 0x10, 0x08, 0x00,

    /* U+002C "," */
    0x56,

    /* U+002D "-" */
    0xf0,

    /* U+002E "." */
    0xc0,

    /* U+002F "/" */
    0x08, 0x44, 0x21, 0x10, 0x84, 0x42, 0x11, 0x88, 0x00,

    /* U+0030 "0" */
    0x3c, 0x42, 0x42, 0x81, 0x81, 0x81, 0x81, 0x81, 0x81, 0x42, 0x42, 0x3c,

    /* U+0031 "1" */
    0x71, 0xa0, 0x40, 0x81, 0x02, 0x04, 0x08, 0x10, 0x20, 0x47, 0xf0,

    /* U+0032 "2" */
    0x79, 0x8a, 0x08, 0x10, 0x20, 0x82, 0x08, 0x20, 0x82, 0x07, 0xf0,

    /* U+0033 "3" */
    0x7c, 0x83, 0x01, 0x01, 0x03, 0x3c, 0x03, 0x01, 0x01, 0x01, 0x82, 0x7c,

    /* U+0034 "4" */
    0x06, 0x05, 0x02, 0x82, 0x42, 0x22, 0x11, 0x09, 0x04, 0xff, 0x81, 0x00,
    0x80, 0x40,

    /* U+0035 "5" */
    0x7e, 0x40, 0x40, 0x40, 0x7c, 0x42, 0x01, 0x01, 0x01, 0x01, 0x82, 0x7c,

    /* U+0036 "6" */
    0x1c, 0x62, 0x40, 0x80, 0xbc, 0xc2, 0x81, 0x81, 0x81, 0x81, 0x42, 0x3c,

    /* U+0037 "7" */
    0xff, 0x01, 0x02, 0x02, 0x04, 0x04, 0x08, 0x08, 0x08, 0x10, 0x10, 0x20,

    /* U+0038 "8" */
    0x3c, 0xc3, 0x81, 0x81, 0xc3, 0x3c, 0xc3, 0x81, 0x81, 0x81, 0x42, 0x3c,

    /* U+0039 "9" */
    0x3c, 0x42, 0x82, 0x81, 0x81, 0x81, 0x43, 0x3d, 0x01, 0x02, 0x46, 0x38,

    /* U+003A ":" */
    0xc3,

    /* U+003B ";" */
    0x50, 0x05, 0x60,

    /* U+003C "<" */
    0x00, 0x40, 0xe1, 0xc1, 0xc0, 0x80, 0x1c, 0x01, 0xc0, 0x0e, 0x00, 0x40,

    /* U+003D "=" */
    0xff, 0xc0, 0x00, 0x03, 0xff,

    /* U+003E ">" */
    0x80, 0x1c, 0x00, 0xe0, 0x0e, 0x00, 0x40, 0xe0, 0xe1, 0xc0, 0x80, 0x00,

    /* U+003F "?" */
    0x7a, 0x10, 0x41, 0x0c, 0x63, 0x08, 0x20, 0x02, 0x08,

    /* U+0040 "@" */
    0x0f, 0xc0, 0x60, 0xc2, 0x01, 0x91, 0xea, 0xc8, 0x66, 0x40, 0x99, 0x02,
    0x64, 0x09, 0x90, 0x27, 0x21, 0xa4, 0x7b, 0x08, 0x00, 0x18, 0x30, 0x1f,
    0x80,

    /* U+0041 "A" */
    0x04, 0x00, 0x80, 0x28, 0x05, 0x01, 0x10, 0x22, 0x08, 0x21, 0x04, 0x3f,
    0x88, 0x09, 0x01, 0x40, 0x10,

    /* U+0042 "B" */
    0xfe, 0x40, 0xe0, 0x30, 0x18, 0x1f, 0xfa, 0x07, 0x01, 0x80, 0xc0, 0x60,
    0x5f, 0xc0,

    /* U+0043 "C" */
    0x1f, 0x10, 0xd0, 0x10, 0x08, 0x04, 0x02, 0x01, 0x00, 0x80, 0x20, 0x08,
    0x63, 0xe0,

    /* U+0044 "D" */
    0xfe, 0x20, 0xc8, 0x0a, 0x01, 0x80, 0x60, 0x18, 0x06, 0x01, 0x80, 0x60,
    0x28, 0x33, 0xf8,

    /* U+0045 "E" */
    0xff, 0x80, 0x80, 0x80, 0x80, 0xff, 0x80, 0x80, 0x80, 0x80, 0x80, 0xff,

    /* U+0046 "F" */
    0xff, 0x02, 0x04, 0x08, 0x1f, 0xa0, 0x40, 0x81, 0x02, 0x04, 0x00,

    /* U+0047 "G" */
    0x1f, 0x88, 0x34, 0x06, 0x00, 0x80, 0x20, 0x08, 0x3e, 0x01, 0x80, 0x50,
    0x12, 0x04, 0x7e,

    /* U+0048 "H" */
    0x80, 0x60, 0x18, 0x06, 0x01, 0x80, 0x7f, 0xf8, 0x06, 0x01, 0x80, 0x60,
    0x18, 0x06, 0x01,

    /* U+0049 "I" */
    0xff, 0xf0,

    /* U+004A "J" */
    0x24, 0x92, 0x49, 0x24, 0x92, 0x70,

    /* U+004B "K" */
    0x81, 0x82, 0x84, 0x88, 0x90, 0xe0, 0xa0, 0x90, 0x88, 0x84, 0x82, 0x81,

    /* U+004C "L" */
    0x81, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x81, 0x02, 0x07, 0xf0,

    /* U+004D "M" */
    0xc0, 0x78, 0x0e, 0x82, 0xd0, 0x5a, 0x0b, 0x22, 0x64, 0x4c, 0x51, 0x8a,
    0x30, 0x86, 0x00, 0xc0, 0x10,

    /* U+004E "N" */
    0xc0, 0x68, 0x1a, 0x06, 0x41, 0x88, 0x62, 0x18, 0x46, 0x09, 0x82, 0x60,
    0x58, 0x16, 0x03,

    /* U+004F "O" */
    0x1f, 0x04, 0x11, 0x01, 0x40, 0x18, 0x03, 0x00, 0x60, 0x0c, 0x01, 0x80,
    0x28, 0x08, 0x82, 0x0f, 0x80,

    /* U+0050 "P" */
    0xfc, 0x82, 0x81, 0x81, 0x81, 0x82, 0xfc, 0x80, 0x80, 0x80, 0x80, 0x80,

    /* U+0051 "Q" */
    0x1f, 0x04, 0x11, 0x01, 0x40, 0x18, 0x03, 0x00, 0x60, 0x0c, 0x01, 0x80,
    0x28, 0x08, 0x83, 0x0f, 0x80, 0x08, 0x00, 0x80,

    /* U+0052 "R" */
    0xfc, 0x41, 0x20, 0x50, 0x28, 0x14, 0x13, 0xf9, 0x04, 0x81, 0x40, 0xa0,
    0x30, 0x10,

    /* U+0053 "S" */
    0x3c, 0xc6, 0x80, 0x80, 0x80, 0x70, 0x1e, 0x03, 0x01, 0x81, 0xc3, 0x7c,

    /* U+0054 "T" */
    0xff, 0x84, 0x02, 0x01, 0x00, 0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02,
    0x01, 0x00,

    /* U+0055 "U" */
    0x80, 0x60, 0x18, 0x06, 0x01, 0x80, 0x60, 0x18, 0x06, 0x01, 0x80, 0x60,
    0x14, 0x08, 0xfc,

    /* U+0056 "V" */
    0x80, 0x30, 0x05, 0x01, 0x20, 0x22, 0x08, 0x41, 0x04, 0x40, 0x88, 0x11,
    0x01, 0x40, 0x28, 0x02, 0x00,

    /* U+0057 "W" */
    0x81, 0x03, 0x02, 0x05, 0x0a, 0x12, 0x14, 0x24, 0x28, 0x44, 0x51, 0x09,
    0x12, 0x12, 0x24, 0x14, 0x50, 0x28, 0xa0, 0x20, 0x80, 0x41, 0x00,

    /* U+0058 "X" */
    0xc1, 0xa0, 0x88, 0x84, 0x41, 0x40, 0x40, 0x20, 0x28, 0x22, 0x11, 0x10,
    0x50, 0x10,

    /* U+0059 "Y" */
    0x80, 0xa0, 0x88, 0x84, 0x41, 0x40, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02,
    0x01, 0x00,

    /* U+005A "Z" */
    0xff, 0xc0, 0x10, 0x08, 0x04, 0x02, 0x01, 0x00, 0x80, 0x40, 0x20, 0x10,
    0x08, 0x03, 0xff,

    /* U+005B "[" */
    0xf2, 0x49, 0x24, 0x92, 0x49, 0xc0,

    /* U+005C "\\" */
    0x86, 0x10, 0x84, 0x10, 0x84, 0x10, 0x84, 0x10, 0x80,

    /* U+005D "]" */
    0xe4, 0x92, 0x49, 0x24, 0x93, 0xc0,

    /* U+005E "^" */
    0x18, 0x3c, 0x42, 0x81,

    /* U+005F "_" */
    0xff,

    /* U+0060 "`" */
    0xc6, 0x30,

    /* U+0061 "a" */
    0x3c, 0x8c, 0x0b, 0xfc, 0x30, 0x60, 0xe3, 0x7a,

    /* U+0062 "b" */
    0x80, 0x80, 0x80, 0xbc, 0xc2, 0x81, 0x81, 0x81, 0x81, 0x81, 0xc2, 0xbc,

    /* U+0063 "c" */
    0x3c, 0x86, 0x04, 0x08, 0x10, 0x20, 0x21, 0x3c,

    /* U+0064 "d" */
    0x01, 0x01, 0x01, 0x3d, 0x43, 0x81, 0x81, 0x81, 0x81, 0x81, 0x43, 0x3d,

    /* U+0065 "e" */
    0x38, 0x8a, 0x0c, 0x1f, 0xf0, 0x20, 0x21, 0x3c,

    /* U+0066 "f" */
    0x3a, 0x11, 0xe4, 0x21, 0x08, 0x42, 0x10, 0x80,

    /* U+0067 "g" */
    0x3d, 0x43, 0x81, 0x81, 0x81, 0x81, 0x81, 0x43, 0x3d, 0x01, 0x42, 0x3c,

    /* U+0068 "h" */
    0x80, 0x80, 0x80, 0xbc, 0xc2, 0x81, 0x81, 0x81, 0x81, 0x81, 0x81, 0x81,

    /* U+0069 "i" */
    0xdf, 0xf0,

    /* U+006A "j" */
    0x24, 0x12, 0x49, 0x24, 0x92, 0x70,

    /* U+006B "k" */
    0x81, 0x02, 0x04, 0x18, 0x51, 0x24, 0x70, 0x91, 0x12, 0x14, 0x10,

    /* U+006C "l" */
    0xff, 0xf0,

    /* U+006D "m" */
    0xbc, 0xf6, 0x38, 0xe0, 0x83, 0x04, 0x18, 0x20, 0xc1, 0x06, 0x08, 0x30,
    0x41, 0x82, 0x08,

    /* U+006E "n" */
    0xbc, 0xc2, 0x81, 0x81, 0x81, 0x81, 0x81, 0x81, 0x81,

    /* U+006F "o" */
    0x3c, 0x42, 0x81, 0x81, 0x81, 0x81, 0x81, 0x42, 0x3c,

    /* U+0070 "p" */
    0xbc, 0xc2, 0x81, 0x81, 0x81, 0x81, 0x81, 0xc2, 0xbc, 0x80, 0x80, 0x80,

    /* U+0071 "q" */
    0x3d, 0x43, 0x81, 0x81, 0x81, 0x81, 0x81, 0x43, 0x3d, 0x01, 0x01, 0x01,

    /* U+0072 "r" */
    0xbe, 0x21, 0x08, 0x42, 0x10, 0x80,

    /* U+0073 "s" */
    0x7d, 0x06, 0x06, 0x07, 0x80, 0xc0, 0xc1, 0x7c,

    /* U+0074 "t" */
    0x42, 0x3e, 0x84, 0x21, 0x08, 0x42, 0x0e,

    /* U+0075 "u" */
    0x81, 0x81, 0x81, 0x81, 0x81, 0x81, 0x81, 0x43, 0x3d,

    /* U+0076 "v" */
    0x80, 0xc0, 0x50, 0x48, 0x22, 0x21, 0x10, 0x50, 0x38, 0x08, 0x00,

    /* U+0077 "w" */
    0x82, 0x0c, 0x10, 0x51, 0x44, 0x8a, 0x24, 0x89, 0x14, 0x50, 0xa2, 0x82,
    0x08, 0x10, 0x40,

    /* U+0078 "x" */
    0xc3, 0x42, 0x24, 0x24, 0x18, 0x24, 0x24, 0x42, 0xc3,

    /* U+0079 "y" */
    0x80, 0xa0, 0x90, 0x44, 0x22, 0x21, 0x10, 0x50, 0x28, 0x0c, 0x04, 0x02,
    0x0e, 0x00,

    /* U+007A "z" */
    0xfe, 0x04, 0x10, 0x41, 0x04, 0x10, 0x40, 0xfe,

    /* U+007B "{" */
    0x19, 0x08, 0x42, 0x10, 0x98, 0x21, 0x08, 0x42, 0x10, 0x60,

    /* U+007C "|" */
    0xff, 0xff,

    /* U+007D "}" */
    0xc1, 0x08, 0x42, 0x10, 0x83, 0x21, 0x08, 0x42, 0x13, 0x00,

    /* U+007E "~" */
    0x78, 0x61, 0xe0,

    /* U+00B0 "°" */
    0x74, 0x63, 0x17, 0x00,

    /* U+00B1 "±" */
    0x08, 0x04, 0x02, 0x1f, 0xf0, 0x80, 0x40, 0x20, 0x00, 0x00, 0x7f, 0xc0,

    /* U+00D7 "×" */
    0x80, 0xa0, 0x88, 0x82, 0x80, 0x80, 0xa0, 0x88, 0x82, 0x80, 0x80,

};

/*---------------------
 *  GLYPH DESCRIPTION
 *--------------------*/

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,
    {.bitmap_index = 0, .adv_w = 82, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 0, .adv_w = 103, .box_w = 1, .box_h = 12, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 2, .adv_w = 118, .box_w = 4, .box_h = 4, .ofs_x = 1, .ofs_y = 8},
    {.bitmap_index = 4, .adv_w = 214, .box_w = 11, .box_h = 11, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 20, .adv_w = 163, .box_w = 7, .box_h = 14, .ofs_x = 2, .ofs_y = -2},
    {.bitmap_index = 33, .adv_w = 243, .box_w = 13, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 53, .adv_w = 200, .box_w = 10, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 68, .adv_w = 70, .box_w = 1, .box_h = 4, .ofs_x = 1, .ofs_y = 8},
    {.bitmap_index = 69, .adv_w = 100, .box_w = 4, .box_h = 14, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 76, .adv_w = 100, .box_w = 4, .box_h = 14, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 83, .adv_w = 128, .box_w = 7, .box_h = 8, .ofs_x = 1, .ofs_y = 4},
    {.bitmap_index = 90, .adv_w = 214, .box_w = 9, .box_h = 9, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 101, .adv_w = 82, .box_w = 2, .box_h = 4, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 102, .adv_w = 92, .box_w = 4, .box_h = 1, .ofs_x = 1, .ofs_y = 4},
    {.bitmap_index = 103, .adv_w = 82, .box_w = 1, .box_h = 2, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 104, .adv_w = 86, .box_w = 5, .box_h = 13, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 113, .adv_w = 163, .box_w = 8, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 125, .adv_w = 163, .box_w = 7, .box_h = 12, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 136, .adv_w = 163, .box_w = 7, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 147, .adv_w = 163, .box_w = 8, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 159, .adv_w = 163, .box_w = 9, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 173, .adv_w = 163, .box_w = 8, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 185, .adv_w = 163, .box_w = 8, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 197, .adv_w = 163, .box_w = 8, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 209, .adv_w = 163, .box_w = 8, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 221, .adv_w = 163, .box_w = 8, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 233, .adv_w = 86, .box_w = 1, .box_h = 8, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 234, .adv_w = 86, .box_w = 2, .box_h = 10, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 237, .adv_w = 214, .box_w = 10, .box_h = 9, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 249, .adv_w = 214, .box_w = 10, .box_h = 4, .ofs_x = 2, .ofs_y = 3},
    {.bitmap_index = 254, .adv_w = 214, .box_w = 10, .box_h = 9, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 266, .adv_w = 136, .box_w = 6, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 275, .adv_w = 256, .box_w = 14, .box_h = 14, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 300, .adv_w = 175, .box_w = 11, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 317, .adv_w = 176, .box_w = 9, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 331, .adv_w = 179, .box_w = 9, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 345, .adv_w = 197, .box_w = 10, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 360, .adv_w = 162, .box_w = 8, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 372, .adv_w = 147, .box_w = 7, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 383, .adv_w = 198, .box_w = 10, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 398, .adv_w = 192, .box_w = 10, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 413, .adv_w = 76, .box_w = 1, .box_h = 12, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 415, .adv_w = 76, .box_w = 3, .box_h = 15, .ofs_x = 0, .ofs_y = -3},
    {.bitmap_index = 421, .adv_w = 168, .box_w = 8, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 433, .adv_w = 143, .box_w = 7, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 444, .adv_w = 221, .box_w = 11, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 461, .adv_w = 192, .box_w = 10, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 476, .adv_w = 202, .box_w = 11, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 493, .adv_w = 154, .box_w = 8, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 505, .adv_w = 202, .box_w = 11, .box_h = 14, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 525, .adv_w = 178, .box_w = 9, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 539, .adv_w = 162, .box_w = 8, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 551, .adv_w = 156, .box_w = 9, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 565, .adv_w = 188, .box_w = 10, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 580, .adv_w = 175, .box_w = 11, .box_h = 12, .ofs_x = -1, .ofs_y = 0},
    {.bitmap_index = 597, .adv_w = 253, .box_w = 15, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 620, .adv_w = 176, .box_w = 9, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 634, .adv_w = 156, .box_w = 9, .box_h = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 648, .adv_w = 176, .box_w = 10, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 663, .adv_w = 100, .box_w = 3, .box_h = 14, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 669, .adv_w = 86, .box_w = 5, .box_h = 13, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 678, .adv_w = 100, .box_w = 3, .box_h = 14, .ofs_x = 2, .ofs_y = -2},
    {.bitmap_index = 684, .adv_w = 214, .box_w = 8, .box_h = 4, .ofs_x = 3, .ofs_y = 8},
    {.bitmap_index = 688, .adv_w = 128, .box_w = 8, .box_h = 1, .ofs_x = 0, .ofs_y = -4},
    {.bitmap_index = 689, .adv_w = 128, .box_w = 4, .box_h = 3, .ofs_x = 1, .ofs_y = 10},
    {.bitmap_index = 691, .adv_w = 157, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 699, .adv_w = 162, .box_w = 8, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 711, .adv_w = 141, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 719, .adv_w = 162, .box_w = 8, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 731, .adv_w = 158, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 739, .adv_w = 90, .box_w = 5, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 747, .adv_w = 162, .box_w = 8, .box_h = 12, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 759, .adv_w = 162, .box_w = 8, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 771, .adv_w = 71, .box_w = 1, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 773, .adv_w = 71, .box_w = 3, .box_h = 15, .ofs_x = -1, .ofs_y = -3},
    {.bitmap_index = 779, .adv_w = 148, .box_w = 7, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 790, .adv_w = 71, .box_w = 1, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 792, .adv_w = 250, .box_w = 13, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 807, .adv_w = 162, .box_w = 8, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 816, .adv_w = 157, .box_w = 8, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 825, .adv_w = 162, .box_w = 8, .box_h = 12, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 837, .adv_w = 162, .box_w = 8, .box_h = 12, .ofs_x = 1, .ofs_y = -3},
    {.bitmap_index = 849, .adv_w = 105, .box_w = 5, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 855, .adv_w = 134, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 863, .adv_w = 100, .box_w = 5, .box_h = 11, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 870, .adv_w = 162, .box_w = 8, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 879, .adv_w = 152, .box_w = 9, .box_h = 9, .ofs_x = -1, .ofs_y = 0},
    {.bitmap_index = 890, .adv_w = 210, .box_w = 13, .box_h = 9, .ofs_x = -1, .ofs_y = 0},
    {.bitmap_index = 905, .adv_w = 152, .box_w = 8, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 914, .adv_w = 152, .box_w = 9, .box_h = 12, .ofs_x = 0, .ofs_y = -3},
    {.bitmap_index = 928, .adv_w = 134, .box_w = 7, .box_h = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 936, .adv_w = 163, .box_w = 5, .box_h = 15, .ofs_x = 2, .ofs_y = -3},
    {.bitmap_index = 946, .adv_w = 86, .box_w = 1, .box_h = 16, .ofs_x = 2, .ofs_y = -4},
    {.bitmap_index = 948, .adv_w = 163, .box_w = 5, .box_h = 15, .ofs_x = 2, .ofs_y = -3},
    {.bitmap_index = 958, .adv_w = 214, .box_w = 10, .box_h = 2, .ofs_x = 2, .ofs_y = 5},
    {.bitmap_index = 961, .adv_w = 128, .box_w = 5, .box_h = 5, .ofs_x = 2, .ofs_y = 7},
    {.bitmap_index = 965, .adv_w = 214, .box_w = 9, .box_h = 10, .ofs_x = 2, .ofs_y = 0},
    {.bitmap_index = 977, .adv_w = 214, .box_w = 9, .box_h = 9, .ofs_x = 2, .ofs_y = 1},
};

/*---------------------
 *  CHARACTER MAPPING
 *--------------------*/

static const uint16_t unicode_list_1[] = {
    0x0, 0x1, 0x27
};

/*Collect the unicode lists and glyph_id offsets*/
static const lv_font_fmt_txt_cmap_t cmaps[] =
{
    {
        .range_start = 32, .range_length = 95, .glyph_id_start = 1,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
    {
        .range_start = 176, .range_length = 40, .glyph_id_start = 96,
        .unicode_list = unicode_list_1, .glyph_id_ofs_list = NULL, .list_length = 3, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
    }
};

/*--------------------
 *  ALL CUSTOM DATA
 *--------------------*/

#if LVGL_VERSION_MAJOR == 8
/*Store all the custom data of the font*/
static  lv_font_fmt_txt_glyph_cache_t cache;
#endif

#if LVGL_VERSION_MAJOR >= 8
static const lv_font_fmt_txt_dsc_t font_dsc = {
#else
static lv_font_fmt_txt_dsc_t font_dsc = {
#endif
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 2,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = 0,
#if LVGL_VERSION_MAJOR == 8
    .cache = &cache
#endif
};

/*-----------------
 *  PUBLIC FONT
 *----------------*/

/*Initialize a public general font descriptor*/
#if LVGL_VERSION_MAJOR >= 8
const lv_font_t qg_font_sans_16 = {
#else
lv_font_t qg_font_sans_16 = {
#endif
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 19,          /*The maximum line height required by the font*/
    .base_line = 4,             /*Baseline measured from the bottom of the line*/
#if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)
    .subpx = LV_FONT_SUBPX_NONE,
#endif
#if LV_VERSION_CHECK(7, 4, 0) || LVGL_VERSION_MAJOR >= 8
    .underline_position = -1,
    .underline_thickness = 1,
#endif
    .dsc = &font_dsc,
#if LV_VERSION_CHECK(8, 2, 0) || LVGL_VERSION_MAJOR >= 9
    .fallback = NULL,
#endif
    .user_data = NULL,
};

#endif /*#if QG_FONT_SANS_16*/
