/* SPDX-License-Identifier: MIT-0 */
/* SPDX-AI-Disclosure: ai-generated */
/* SPDX-AI-Model: claude-opus-5-5 */
/* SPDX-AI-Provider: Anthropic */
/**
 * @file    example_art.h
 * @brief   The example images, compiled in from example_art.c (generated by
 *          examples/art/make_art.py). Each is a whole 8-bit BMP file.
 */
#ifndef EXAMPLE_ART_H
#define EXAMPLE_ART_H
#include <stdint.h>

extern const uint8_t  img_logo[];    /* 240x48 banner                     */
extern const uint32_t img_logo_size;
extern const uint8_t  img_star[];    /* 32x32, transparent                */
extern const uint32_t img_star_size;
extern const uint8_t  img_ship[];    /* 16x16 pixel art, transparent      */
extern const uint32_t img_ship_size;
extern const uint8_t  img_scene[];   /* 240x160 landscape                 */
extern const uint32_t img_scene_size;

#endif /* EXAMPLE_ART_H */
