#!/usr/bin/env python3
# SPDX-License-Identifier: MIT-0
# SPDX-AI-Disclosure: ai-generated
# SPDX-AI-Model: claude-opus-5-5
# SPDX-AI-Provider: Anthropic
"""Draw the example art from scratch (so it carries no licence questions),
then convert it to examples/example_art.c with tools/img2bmp8.py.
Run from the repository root:  python3 examples/art/make_art.py"""
import math, os, subprocess, sys
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
def font(size):
    try: return ImageFont.truetype(FONT, size)
    except OSError: return ImageFont.load_default()

# logo: 240x48 banner. The gradient runs TOP TO BOTTOM on purpose: RLE8
# compresses runs of identical pixels along each row, so a vertical gradient
# (each row one colour) shrinks to almost nothing, while a horizontal one
# (every pixel in a row different) doesn't compress at all.
im = Image.new("RGB", (240, 48))
d = ImageDraw.Draw(im)
for y in range(48):
    t = y / 47
    d.line([(0, y), (239, y)], fill=(int(20 + 40 * t), int(40 + 80 * t), int(120 + 100 * t)))
d.text((122, 26), "QG4P", font=font(32), fill=(0, 0, 0), anchor="mm")
d.text((120, 24), "QG4P", font=font(32), fill=(255, 230, 120), anchor="mm")
im.save(os.path.join(HERE, "logo.png"))

# star: 32x32, transparent background
im = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
d = ImageDraw.Draw(im)
pts = []
for i in range(10):
    r = 15 if i % 2 == 0 else 6.5
    a = math.radians(-90 + i * 36)
    pts.append((16 + r * math.cos(a), 16.5 + r * math.sin(a)))
d.polygon(pts, fill=(255, 210, 40, 255), outline=(180, 110, 0, 255))
im.save(os.path.join(HERE, "star.png"))

# ship: 16x16 pixel-art rocket
art = [
    ".......##.......",
    "......#ww#......",
    "......#ww#......",
    ".....#wwww#.....",
    ".....#wbbw#.....",
    ".....#wbbw#.....",
    ".....#wwww#.....",
    ".....#wwww#.....",
    "....r#wwww#r....",
    "...rr#wwww#rr...",
    "..rrr#wwww#rrr..",
    "..rr.#wwww#.rr..",
    "......#oo#......",
    ".....oyyyyo.....",
    "......oyyo......",
    ".......oo.......",
]
pal = {"#": (60, 60, 80, 255), "w": (230, 230, 240, 255), "b": (80, 160, 255, 255),
       "r": (220, 50, 50, 255), "o": (255, 140, 0, 255), "y": (255, 230, 80, 255), ".": (0, 0, 0, 0)}
im = Image.new("RGBA", (16, 16))
im.putdata([pal[c] for row in art for c in row])
im.save(os.path.join(HERE, "ship.png"))

# scene: 240x160 dusk over hills
W, H = 240, 160
im = Image.new("RGB", (W, H))
px = im.load()
for y in range(H):
    t = y / H
    for x in range(W):
        px[x, y] = (int(30 + 190 * t), int(40 + 90 * t), int(110 + 40 * t))
d = ImageDraw.Draw(im)
d.ellipse([150, 40, 190, 80], fill=(255, 200, 120))
for i, (base, amp, col) in enumerate([(105, 18, (60, 70, 110)), (125, 14, (40, 50, 85)), (145, 9, (25, 30, 60))]):
    pts = [(x, base - amp * math.sin(x / (22 + 9 * i) + 2 * i)) for x in range(0, W + 1, 4)]
    d.polygon(pts + [(W, H), (0, H)], fill=col)
im.save(os.path.join(HERE, "scene.png"))

# convert to one C file
T = os.path.join(ROOT, "tools", "img2bmp8.py")
parts = []
for name, opts in (("logo", ["--no-dither"]), ("star", ["--no-dither"]), ("ship", ["--no-dither"]), ("scene", [])):
    src = os.path.join(HERE, name + ".png")
    subprocess.run([sys.executable, T, src, *opts, "--out", os.path.join(HERE, name + ".bmp"),
                    "--c-array", "img_" + name], check=True)
    c = os.path.join(HERE, "img_" + name + ".c")
    parts.append(open(c).read()); os.remove(c)
out = os.path.join(ROOT, "examples", "example_art.c")
with open(out, "w") as fh:
    fh.write("/* SPDX-License-Identifier: MIT-0 */\n/* SPDX-AI-Disclosure: ai-generated */\n"
             "/* SPDX-AI-Model: claude-opus-5-5 */\n/* SPDX-AI-Provider: Anthropic */\n/* The example art, generated by examples/art/make_art.py. */\n\n")
    fh.write("\n".join(p.replace("#include <stdint.h>\n\n", "") if i else p for i, p in enumerate(parts)))
print("wrote", out)
